# Generated by Django 4.2.5 on 2024-07-12 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='chat_history',
            field=models.JSONField(default=list),
        ),
    ]
