# Generated by Django 4.2.5 on 2024-07-12 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0002_chatbot_chat_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbot',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gemini_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
